resource "aws_sns_topic" "cloudwatch_alerts" {
  name              = "${var.project_name}-${var.environment}-alerts"
  kms_master_key_id = "alias/aws/sns"
}

resource "aws_sns_topic_subscription" "email_alerts" {
  topic_arn = aws_sns_topic.cloudwatch_alerts.arn
  protocol  = "email"
  endpoint  = "Hassanhi3@icloud.com"
}

# CloudWatch alarm for high ECS CPU
resource "aws_cloudwatch_metric_alarm" "ecs_high_cpu" {

  # Name shown for the alarm in CloudWatch
  alarm_name          = "${var.project_name}-${var.environment}-ecs-high-cpu"
  comparison_operator = "GreaterThanThreshold" # Alarm triggers when the metric goes ABOVE the threshold
  evaluation_periods  = 2                      # Number of periods CloudWatch checks / # 2 periods x 60 seconds = 2 minutes
  metric_name         = "CPUUtilization"
  namespace           = "AWS/ECS" # Tells CloudWatch this metric comes from ECS
  period              = 60        # seconds
  statistic           = "Average" # Takes the AVERAGE CPU usage during each 60-second period
  threshold           = 80

  dimensions = { # Specifies which ECS service that CloudWatch should monitor
    ClusterName = aws_ecs_cluster.main.name
    ServiceName = aws_ecs_service.main.name
  }
  # this means that when the alarm is triggered cloudwatch sends a  message to my email via sns topic
  alarm_actions = [
    aws_sns_topic.cloudwatch_alerts.arn
  ]
}

# CloudWatch alarm for ALB 5xx errors
resource "aws_cloudwatch_metric_alarm" "alb_5xx" {

  alarm_name          = "${var.project_name}-${var.environment}-alb-5xx"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 1                        # Only 1 period needs to breach
  metric_name         = "HTTPCode_ELB_5XX_Count" # Counts 5xx errors generated by the ALB itself
  namespace           = "AWS/ApplicationELB"     # Metric belongs to Application Load Balancer
  period              = 60                       # seconds
  statistic           = "Sum"                    # Adds together all 5xx errors during the 60-second period
  threshold           = 5                        # sends alarm if there are more than 5 errors in 1 minute

  dimensions = { # dimensions tell CloudWatch which ALB to monitor
    LoadBalancer = aws_lb.main.arn_suffix
  }

  alarm_actions = [
    aws_sns_topic.cloudwatch_alerts.arn
  ]
}

# CloudWatch alarm for high ECS memory
resource "aws_cloudwatch_metric_alarm" "ecs_high_memory" {

  # High Memory alarm in CloudWatch
  alarm_name          = "${var.project_name}-${var.environment}-ecs-high-memory"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 2
  metric_name         = "MemoryUtilization"
  namespace           = "AWS/ECS"
  period              = 60
  statistic           = "Average"
  threshold           = 80

  dimensions = {
    ClusterName = aws_ecs_cluster.main.name
    ServiceName = aws_ecs_service.main.name
  }

  alarm_actions = [
    aws_sns_topic.cloudwatch_alerts.arn
  ]
}

# CloudWatch alarm for high ECS ALB unhealthy targets
resource "aws_cloudwatch_metric_alarm" "alb_unhealthy_targets" {

  #ALB unhealthy CloudWatch
  alarm_name          = "${var.project_name}-${var.environment}-unhealthy-alb-targets"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 1
  metric_name         = "UnHealthyHostCountation"
  namespace           = "AWS/ApplicationELB"
  period              = 60
  statistic           = "Average"
  threshold           = 0

  dimensions = {
    TargetGroup  = aws_lb_target_group.ecs_target_group.arn_suffix
    LoadBalancer = aws_lb.main.arn_suffix
  }

  alarm_actions = [
    aws_sns_topic.cloudwatch_alerts.arn
  ]
}

# CloudWatch alarm alb response times
resource "aws_cloudwatch_metric_alarm" "alb_response_time" {
  alarm_name          = "${var.project_name}-${var.environment}-alb-response-time"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = 2
  metric_name         = "TargetResponseTime"
  namespace           = "AWS/ApplicationELB"
  period              = 60
  statistic           = "Average"
  threshold           = 1

  dimensions = {
    LoadBalancer = aws_lb.main.arn_suffix
    TargetGroup  = aws_lb_target_group.ecs_target_group.arn_suffix
  }

  alarm_actions = [
    aws_sns_topic.cloudwatch_alerts.arn
  ]
}

#ECS running tasks alarm for under 1 task running
resource "aws_cloudwatch_metric_alarm" "low_ecs_running_tasks" {
  alarm_name          = "${var.project_name}-${var.environment}-low-ecs-running-tasks"
  comparison_operator = "LessThanThreshold"
  evaluation_periods  = 1
  metric_name         = "RunningTaskCount"
  namespace           = "AWS/ECS"
  period              = 60
  statistic           = "Average"
  threshold           = 1

  dimensions = {
    ClusterName = aws_ecs_cluster.main.name
    ServiceName = aws_ecs_service.main.name
  }

  alarm_actions = [
    aws_sns_topic.cloudwatch_alerts.arn
  ]
}

resource "aws_flow_log" "main" {
  iam_role_arn    = aws_iam_role.vpc_flow_logs.arn
  log_destination = aws_cloudwatch_log_group.vpc_flow_logs.arn
  traffic_type    = "ALL"
  vpc_id          = aws_vpc.main.id
}