name: CD Workflow

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI Workflow"]
    types:
      - completed

env:
  DEPLOY_SHA: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.sha }}
  TF_VAR_domain_name: ${{ vars.DOMAIN_NAME }}
  TF_VAR_route53_zone_id: ${{ vars.ROUTE53_ZONE_ID }}

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.DEPLOY_SHA }}

      - name: Confirm checkout
        run: |
          echo "Checking out code and commit ${DEPLOY_SHA} for CD workflow"

      - name: OpenID Connect
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Test AWS Authentication
        run: |
          aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Set up Docker Buildx for multi-platform image builds.

      - name: Build and push Docker image # Cosign image signing
        uses: docker/build-push-action@v6
        with:
          context: ./ec2-legacy-app/app
          platforms: linux/arm64
          push: true # using the sha tag so ecs can deploy a specific immutable version that we can track which commit is running.
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/ec2-legacy-app:latest
            ${{ steps.login-ecr.outputs.registry }}/ec2-legacy-app:${{ env.DEPLOY_SHA }}

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ec2-legacy-app/terraform-ecs
        run: terraform init

      - name: Terraform format
        working-directory: ec2-legacy-app/terraform-ecs
        run: terraform fmt -check # formatting without making changes in code

      - name: Terraform Plan
        working-directory: ec2-legacy-app/terraform-ecs
        run: |
          terraform plan \
            -var="container_image=${{ steps.login-ecr.outputs.registry }}/ec2-legacy-app:${{ env.DEPLOY_SHA }}" \
            -out=tfplan

      - name: Terraform Apply
        working-directory: ec2-legacy-app/terraform-ecs
        run: terraform apply -auto-approve tfplan # auto approve so that worklfow can run w/out manual intervention.
        # In production, i will remove this and approve manually.

      - name: Trigger ECS Service Deployment
        run: |
          aws --version
          aws ecs update-service \
            --cluster ec2-to-ecs-migration-production-cluster \
            --service ec2-to-ecs-migration-app-service \
            --force-new-deployment \
            --region eu-west-2

      - name: Wait for ECS service to stabilise
        run: |
          aws ecs wait services-stable \
            --cluster ec2-to-ecs-migration-production-cluster \
            --services ec2-to-ecs-migration-app-service \
            --region eu-west-2

      - name: Smoke test
        run: |
          curl --fail http://api.legacy-api-demo.co.uk/health