name: Destroy Terraform Resources

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "destroy" to confirm'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    if: ${{ github.event.inputs.confirm == 'destroy' }}
    runs-on: ubuntu-latest
    environment: Production
    env:
      TF_VAR_domain_name: ${{ vars.DOMAIN_NAME }}
      TF_VAR_route53_zone_id: ${{ vars.ROUTE53_ZONE_ID }}
    defaults:
      run:
        working-directory: ec2-legacy-app/terraform-ecs

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: OpenID Connect
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2
          audience: sts.amazonaws.com # tells AWS that this is an OIDC request

      - name: Terraform Setup
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ec2-legacy-app/terraform-ecs
        run: terraform init

      - name: Terraform Validate
        working-directory: ec2-legacy-app/terraform-ecs
        run: terraform validate # validating so we don't accidentally destroy resources.

      - name: Terraform Destroy
        run: |
          terraform destroy -auto-approve -input=false -var="container_image=unused"
          echo "Terraform destroy completed successfully."